// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuTSQs_XwALfQqG6f_101E4fprL5PXo8',
    appId: '1:110809534209:web:b651ff6b7ed039f8a25500',
    messagingSenderId: '110809534209',
    projectId: 'ijob-7f2f7',
    authDomain: 'ijob-7f2f7.firebaseapp.com',
    databaseURL: 'https://ijob-7f2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ijob-7f2f7.firebasestorage.app',
    measurementId: 'G-258MCF04BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHmNilFNs__mO61jnsR0lFIo1WyhgSP78',
    appId: '1:110809534209:android:a140cd87407355dca25500',
    messagingSenderId: '110809534209',
    projectId: 'ijob-7f2f7',
    databaseURL: 'https://ijob-7f2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ijob-7f2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_FYD1ei4NCUFHuf7bdhHlVflqj19O8B0',
    appId: '1:110809534209:ios:d9b7004b079c187da25500',
    messagingSenderId: '110809534209',
    projectId: 'ijob-7f2f7',
    databaseURL: 'https://ijob-7f2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ijob-7f2f7.firebasestorage.app',
    iosBundleId: 'com.example.testetelaprincipal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_FYD1ei4NCUFHuf7bdhHlVflqj19O8B0',
    appId: '1:110809534209:ios:d9b7004b079c187da25500',
    messagingSenderId: '110809534209',
    projectId: 'ijob-7f2f7',
    databaseURL: 'https://ijob-7f2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ijob-7f2f7.firebasestorage.app',
    iosBundleId: 'com.example.testetelaprincipal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLuTSQs_XwALfQqG6f_101E4fprL5PXo8',
    appId: '1:110809534209:web:5d05baaf97316fe7a25500',
    messagingSenderId: '110809534209',
    projectId: 'ijob-7f2f7',
    authDomain: 'ijob-7f2f7.firebaseapp.com',
    databaseURL: 'https://ijob-7f2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ijob-7f2f7.firebasestorage.app',
    measurementId: 'G-5RESG911N8',
  );
}
